[build]
  publish = "build/"
  command = "npm run build"
  [[headers]]
  for = "/src/fonts/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000'''
  for = "/src/fonts/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"
  for = "/src/fonts/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"
