[build]
  publish = "build/"
  command = "npm run build"
  [[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"
    for = "/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"
  